openapi: 3.0.0
info:
  title: Guestbook API
  version: 1.0.0
  description: API Gateway for serverless guestbook application

paths:
  /:
    get:
      summary: Main page
      x-yc-apigateway-integration:
        type: object_storage
        bucket: guestbook-frontend-2002
        object: index.html
        presigned_redirect: false
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '200':
          description: Main page

  /style.css:
    get:
      summary: CSS styles
      x-yc-apigateway-integration:
        type: object_storage
        bucket: guestbook-frontend-2002
        object: style.css
        presigned_redirect: false
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '200':
          description: CSS file

  /app.js:
    get:
      summary: JavaScript application
      x-yc-apigateway-integration:
        type: object_storage
        bucket: guestbook-frontend-2002
        object: app.js
        presigned_redirect: false
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '200':
          description: JavaScript file

  /api/info:
    get:
      summary: Backend information
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba1jo5kenut1jgu5asb
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '200':
          description: Backend info

  /api/messages:
    get:
      summary: Get messages
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba1jo5kenut1jgu5asb
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '200':
          description: List of messages

    post:
      summary: Post a new message
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba1jo5kenut1jgu5asb
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '201':
          description: Message created

  /api/ping-fn:
    get:
      summary: Ping function
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e9h14bedbkbfctq94j
        service_account_id: aje8tueemibgatuv98bd
      responses:
        '200':
          description: Pong response
